services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      # --- PERUBAHAN DI SINI ---
      # Menggunakan kredensial database utama dari service 'postgres'
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB:-n8n}
      DB_POSTGRESDB_USER: ${POSTGRES_USER:-postgres}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_ROOT_PASSWORD} # Menggunakan password postgres utama
      
      # Menambahkan variabel untuk memperbaiki peringatan perizinan
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      
      # URL untuk webhook dan editor
      WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_EDITOR_BASE_URL: ${N8N_EDITOR_URL}

      # Zona Waktu
      GENERIC_TIMEZONE: Asia/Jakarta
      TZ: Asia/Jakarta
    volumes:
      - n8n_data:/home/node/.n8n 
    networks:
      - shared-infrastructure

volumes:
  n8n_data:
  n8n_files:

networks:
  shared-infrastructure:
    external: true